# -*- coding: utf-8 -*-
"""
宜昌市 POI - WGS84 经纬度真值表
==============================

所有 POI 用 WGS84 (lng, lat) 度数定义，作为"真理之源"。
通过 pyproj 精确投影到 EPSG:4546 (CGCS2000 / 3°GK zone 37 / CM 111°E) 米级。

坐标系对照：
- WGS84 (EPSG:4326): 经度 111.20-111.50°E, 纬度 30.65-30.78°N
- EPSG:4546 米级: X(北向) 3,392,000~3,406,000m, Y(东向) 515,000~545,000m
"""

# ============================================================================
# 宜昌核心主城 POI 列表（WGS84 经纬度）
# ============================================================================
# 字段说明：
#   name: POI 名称
#   level1: 百度一级分类
#   level2: 百度二级分类
#   lng: WGS84 经度
#   lat: WGS84 纬度
#   weight: 采样权重
#   domain: 4 领域
#   element: 5 要素
#   area: 区域标签
#   address_hint: 地址提示
#   radius_m: 影响半径（米），默认 300

YICHANG_POIS_LNGLAT = [
    # ============= 核心商圈 =============
    {"name": "解放路步行街", "level1": "购物", "level2": "步行街/商业街",
     "lng": 111.2880, "lat": 30.6920, "weight": 2.0, "domain": "urban_operation", "element": "service",
     "area": "西陵-解放路", "address_hint": "西陵区解放路步行街中心"},
    {"name": "夷陵广场", "level1": "休闲娱乐", "level2": "休闲广场",
     "lng": 111.2900, "lat": 30.6960, "weight": 1.8, "domain": "urban_operation", "element": "event",
     "area": "西陵-夷陵广场", "address_hint": "西陵区夷陵广场"},
    {"name": "铁路坝商圈", "level1": "购物", "level2": "百货商场",
     "lng": 111.3050, "lat": 30.6960, "weight": 1.5, "domain": "urban_operation", "element": "service",
     "area": "西陵-铁路坝", "address_hint": "西陵区铁路坝"},
    {"name": "CBD 万达广场", "level1": "购物", "level2": "购物中心",
     "lng": 111.3120, "lat": 30.7020, "weight": 2.2, "domain": "urban_operation", "element": "event",
     "area": "西陵-CBD", "address_hint": "西陵区沿江大道万达广场"},
    {"name": "兴发广场", "level1": "购物", "level2": "购物中心",
     "lng": 111.2980, "lat": 30.6970, "weight": 1.4, "domain": "urban_operation", "element": "service",
     "area": "西陵-兴发", "address_hint": "西陵区兴发广场"},
    {"name": "卓悦广场", "level1": "购物", "level2": "购物中心",
     "lng": 111.3020, "lat": 30.7000, "weight": 1.0, "domain": "urban_operation", "element": "service",
     "area": "西陵-卓悦", "address_hint": "西陵区卓悦广场"},
    {"name": "水悦城", "level1": "购物", "level2": "购物中心",
     "lng": 111.3080, "lat": 30.7030, "weight": 1.2, "domain": "urban_operation", "element": "service",
     "area": "西陵-水悦城", "address_hint": "西陵区水悦城"},
    {"name": "太古里（西陵）", "level1": "购物", "level2": "购物中心",
     "lng": 111.3180, "lat": 30.7070, "weight": 1.0, "domain": "urban_operation", "element": "service",
     "area": "西陵-太古里", "address_hint": "西陵区太古里"},
    {"name": "伍家岗万达", "level1": "购物", "level2": "购物中心",
     "lng": 111.3680, "lat": 30.7280, "weight": 1.6, "domain": "urban_operation", "element": "service",
     "area": "伍家-万达", "address_hint": "伍家岗区万达广场"},
    {"name": "国贸大厦", "level1": "购物", "level2": "百货商场",
     "lng": 111.2940, "lat": 30.6960, "weight": 1.3, "domain": "urban_operation", "element": "service",
     "area": "西陵-国贸", "address_hint": "西陵区国贸大厦"},
    {"name": "大洋百货", "level1": "购物", "level2": "百货商场",
     "lng": 111.2930, "lat": 30.6940, "weight": 1.2, "domain": "urban_operation", "element": "service",
     "area": "西陵-大洋", "address_hint": "西陵区大洋百货"},
    {"name": "新世纪百货", "level1": "购物", "level2": "百货商场",
     "lng": 111.2910, "lat": 30.6930, "weight": 1.0, "domain": "urban_operation", "element": "service",
     "area": "西陵-新世纪", "address_hint": "西陵区新世纪百货"},
    {"name": "雅斯百货（CBD 店）", "level1": "购物", "level2": "百货商场",
     "lng": 111.3130, "lat": 30.7030, "weight": 0.9, "domain": "urban_operation", "element": "service",
     "area": "西陵-雅斯", "address_hint": "西陵区雅斯百货"},
    {"name": "雅斯广场（伍家店）", "level1": "购物", "level2": "购物中心",
     "lng": 111.3640, "lat": 30.7280, "weight": 1.1, "domain": "urban_operation", "element": "service",
     "area": "伍家-雅斯", "address_hint": "伍家岗区雅斯广场"},
    {"name": "北山超市（CBD）", "level1": "购物", "level2": "超市",
     "lng": 111.3110, "lat": 30.7020, "weight": 0.7, "domain": "urban_operation", "element": "service",
     "area": "西陵-北山", "address_hint": "西陵区北山超市"},
    {"name": "东方超市（伍家）", "level1": "购物", "level2": "超市",
     "lng": 111.3660, "lat": 30.7290, "weight": 0.7, "domain": "urban_operation", "element": "service",
     "area": "伍家-东方", "address_hint": "伍家岗区东方超市"},
    {"name": "悦活里超市", "level1": "购物", "level2": "超市",
     "lng": 111.3050, "lat": 30.6980, "weight": 0.5, "domain": "urban_operation", "element": "service",
     "area": "西陵-悦活里", "address_hint": "西陵区悦活里"},

    # ============= 二马路历史街区（详，最高密度） =============
    {"name": "二马路（主街）", "level1": "道路", "level2": "城市支路",
     "lng": 111.2750, "lat": 30.6880, "weight": 2.5, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-二马路", "address_hint": "西陵区二马路", "radius_m": 400},
    {"name": "大南门", "level1": "旅游景点", "level2": "文物古迹",
     "lng": 111.2720, "lat": 30.6850, "weight": 2.0, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-大南门", "address_hint": "西陵区大南门"},
    {"name": "红星路", "level1": "道路", "level2": "城市支路",
     "lng": 111.2800, "lat": 30.6900, "weight": 1.5, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-红星路", "address_hint": "西陵区红星路"},
    {"name": "献福路", "level1": "道路", "level2": "城市支路",
     "lng": 111.2740, "lat": 30.6890, "weight": 1.4, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-献福路", "address_hint": "西陵区献福路"},
    {"name": "樵湖岭", "level1": "生活服务", "level2": "公用事业",
     "lng": 111.2780, "lat": 30.6920, "weight": 1.3, "domain": "urban_renewal", "element": "facility",
     "area": "西陵-樵湖岭", "address_hint": "西陵区樵湖岭"},
    {"name": "文庙（西陵）", "level1": "旅游景点", "level2": "文物古迹",
     "lng": 111.2730, "lat": 30.6880, "weight": 1.8, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-文庙", "address_hint": "西陵区文庙"},
    {"name": "古佛寺", "level1": "旅游景点", "level2": "寺庙",
     "lng": 111.2790, "lat": 30.6900, "weight": 1.2, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-古佛寺", "address_hint": "西陵区古佛寺"},
    {"name": "西陵剧场", "level1": "休闲娱乐", "level2": "剧院",
     "lng": 111.2720, "lat": 30.6870, "weight": 1.1, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-二马路", "address_hint": "西陵区二马路西陵剧场"},
    {"name": "二马路老茶馆（老字号）", "level1": "美食", "level2": "茶座",
     "lng": 111.2755, "lat": 30.6885, "weight": 1.6, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-二马路", "address_hint": "西陵区二马路老茶馆"},
    {"name": "九码头（老字号）", "level1": "美食", "level2": "中餐厅",
     "lng": 111.2760, "lat": 30.6875, "weight": 1.5, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-二马路", "address_hint": "西陵区二马路九码头"},
    {"name": "陶然居（二马路店）", "level1": "美食", "level2": "中餐厅",
     "lng": 111.2745, "lat": 30.6880, "weight": 1.0, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-二马路", "address_hint": "西陵区二马路陶然居"},
    {"name": "老宜昌（老字号）", "level1": "美食", "level2": "中餐厅",
     "lng": 111.2740, "lat": 30.6875, "weight": 1.2, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-二马路", "address_hint": "西陵区二马路老宜昌"},

    # ============= 公共服务 =============
    {"name": "宜昌市民中心", "level1": "政府机构", "level2": "各级政府",
     "lng": 111.2910, "lat": 30.6940, "weight": 0.8, "domain": "urban_governance", "element": "service",
     "area": "西陵-市民中心", "address_hint": "西陵区市民中心"},
    {"name": "西陵区政府", "level1": "政府机构", "level2": "各级政府",
     "lng": 111.2900, "lat": 30.6930, "weight": 0.6, "domain": "urban_governance", "element": "facility",
     "area": "西陵-政府", "address_hint": "西陵区西陵区政府"},
    {"name": "伍家岗区政府", "level1": "政府机构", "level2": "各级政府",
     "lng": 111.3650, "lat": 30.7330, "weight": 0.6, "domain": "urban_governance", "element": "facility",
     "area": "伍家-政府", "address_hint": "伍家岗区伍家岗区政府"},
    {"name": "宜昌市规划局", "level1": "政府机构", "level2": "行政单位",
     "lng": 111.2930, "lat": 30.6950, "weight": 0.4, "domain": "urban_planning", "element": "facility",
     "area": "西陵-规划", "address_hint": "西陵区规划局"},
    {"name": "宜昌市住建局", "level1": "政府机构", "level2": "行政单位",
     "lng": 111.2920, "lat": 30.6945, "weight": 0.4, "domain": "urban_renewal", "element": "facility",
     "area": "西陵-住建", "address_hint": "西陵区住建局"},
    {"name": "宜昌市城管委", "level1": "政府机构", "level2": "行政单位",
     "lng": 111.2940, "lat": 30.6940, "weight": 0.5, "domain": "urban_governance", "element": "facility",
     "area": "西陵-城管", "address_hint": "西陵区城管委"},
    {"name": "宜昌市公安局", "level1": "政府机构", "level2": "公检法机构",
     "lng": 111.2950, "lat": 30.6950, "weight": 0.4, "domain": "urban_governance", "element": "facility",
     "area": "西陵-公安", "address_hint": "西陵区公安局"},
    {"name": "12345 政务服务热线", "level1": "政府机构", "level2": "行政单位",
     "lng": 111.2910, "lat": 30.6940, "weight": 0.3, "domain": "urban_governance", "element": "service",
     "area": "西陵-12345", "address_hint": "西陵区12345受理中心"},
    {"name": "西陵区市民服务中心", "level1": "政府机构", "level2": "行政单位",
     "lng": 111.2750, "lat": 30.6900, "weight": 0.5, "domain": "urban_governance", "element": "service",
     "area": "西陵-二马路", "address_hint": "西陵区市民服务中心（樵湖岭）"},
    {"name": "宜昌市中心医院", "level1": "医疗", "level2": "综合医院",
     "lng": 111.2990, "lat": 30.7020, "weight": 0.9, "domain": "urban_governance", "element": "service",
     "area": "西陵-中心医院", "address_hint": "西陵区中心医院"},
    {"name": "宜昌市第一人民医院", "level1": "医疗", "level2": "综合医院",
     "lng": 111.2850, "lat": 30.6910, "weight": 0.8, "domain": "urban_governance", "element": "service",
     "area": "西陵-一医院", "address_hint": "西陵区一医院"},
    {"name": "宜昌市第二人民医院", "level1": "医疗", "level2": "综合医院",
     "lng": 111.2810, "lat": 30.6900, "weight": 0.7, "domain": "urban_governance", "element": "service",
     "area": "西陵-二医院", "address_hint": "西陵区二医院"},
    {"name": "宜昌市中医医院", "level1": "医疗", "level2": "专科医院",
     "lng": 111.2960, "lat": 30.6990, "weight": 0.6, "domain": "urban_governance", "element": "service",
     "area": "西陵-中医院", "address_hint": "西陵区中医院"},
    {"name": "伍家医院", "level1": "医疗", "level2": "综合医院",
     "lng": 111.3610, "lat": 30.7300, "weight": 0.6, "domain": "urban_governance", "element": "service",
     "area": "伍家-医院", "address_hint": "伍家岗区伍家医院"},
    {"name": "三峡大学附属仁和医院", "level1": "医疗", "level2": "综合医院",
     "lng": 111.2930, "lat": 30.7080, "weight": 0.5, "domain": "urban_governance", "element": "service",
     "area": "西陵-仁和", "address_hint": "西陵区仁和医院"},
    {"name": "西陵区疾控中心", "level1": "医疗", "level2": "疾控中心",
     "lng": 111.2900, "lat": 30.6930, "weight": 0.3, "domain": "urban_governance", "element": "service",
     "area": "西陵-疾控", "address_hint": "西陵区疾控中心"},
    {"name": "三峡大学", "level1": "教育培训", "level2": "高等院校",
     "lng": 111.2920, "lat": 30.7080, "weight": 1.2, "domain": "urban_operation", "element": "service",
     "area": "西陵-三大学", "address_hint": "西陵区三峡大学", "radius_m": 600},
    {"name": "宜昌一中", "level1": "教育培训", "level2": "中学",
     "lng": 111.2840, "lat": 30.6920, "weight": 0.7, "domain": "urban_operation", "element": "service",
     "area": "西陵-一中", "address_hint": "西陵区宜昌一中"},
    {"name": "夷陵中学", "level1": "教育培训", "level2": "中学",
     "lng": 111.2810, "lat": 30.6970, "weight": 0.6, "domain": "urban_operation", "element": "service",
     "area": "西陵-夷陵中学", "address_hint": "西陵区夷陵中学"},
    {"name": "宜昌市二中", "level1": "教育培训", "level2": "中学",
     "lng": 111.2860, "lat": 30.6940, "weight": 0.5, "domain": "urban_operation", "element": "service",
     "area": "西陵-二中", "address_hint": "西陵区宜昌二中"},
    {"name": "宜昌市实验小学", "level1": "教育培训", "level2": "小学",
     "lng": 111.2890, "lat": 30.6930, "weight": 0.4, "domain": "urban_operation", "element": "service",
     "area": "西陵-实验小学", "address_hint": "西陵区实验小学"},
    {"name": "西陵区实验小学", "level1": "教育培训", "level2": "小学",
     "lng": 111.2800, "lat": 30.6890, "weight": 0.4, "domain": "urban_operation", "element": "service",
     "area": "西陵-西实小", "address_hint": "西陵区西陵实验小学"},
    {"name": "伍家岗区实验小学", "level1": "教育培训", "level2": "小学",
     "lng": 111.3610, "lat": 30.7290, "weight": 0.4, "domain": "urban_operation", "element": "service",
     "area": "伍家-伍实小", "address_hint": "伍家岗区实验小学"},
    {"name": "伍家岗区幼儿园（示范）", "level1": "教育培训", "level2": "幼儿园",
     "lng": 111.3600, "lat": 30.7310, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "伍家-幼儿园", "address_hint": "伍家岗区示范幼儿园"},

    # ============= 交通设施 =============
    {"name": "宜昌站", "level1": "交通设施", "level2": "火车站",
     "lng": 111.3090, "lat": 30.7030, "weight": 1.5, "domain": "urban_governance", "element": "facility",
     "area": "西陵-宜昌站", "address_hint": "西陵区宜昌站", "radius_m": 500},
    {"name": "宜昌东站", "level1": "交通设施", "level2": "火车站",
     "lng": 111.3960, "lat": 30.7400, "weight": 1.6, "domain": "urban_governance", "element": "facility",
     "area": "伍家-宜昌东", "address_hint": "伍家岗区宜昌东站", "radius_m": 500},
    {"name": "三峡机场", "level1": "交通设施", "level2": "飞机场",
     "lng": 111.4800, "lat": 30.7800, "weight": 1.0, "domain": "urban_governance", "element": "facility",
     "area": "猇亭-三峡机场", "address_hint": "猇亭区三峡机场", "radius_m": 1000},
    {"name": "宜昌港（客运）", "level1": "交通设施", "level2": "港口",
     "lng": 111.2750, "lat": 30.6910, "weight": 0.6, "domain": "urban_governance", "element": "facility",
     "area": "西陵-宜昌港", "address_hint": "西陵区宜昌港"},
    {"name": "宜昌汽车客运中心站", "level1": "交通设施", "level2": "长途汽车站",
     "lng": 111.3000, "lat": 30.7020, "weight": 0.8, "domain": "urban_governance", "element": "facility",
     "area": "西陵-客运中心", "address_hint": "西陵区汽车客运中心"},
    {"name": "夷陵长江大桥", "level1": "交通设施", "level2": "桥",
     "lng": 111.2700, "lat": 30.7010, "weight": 0.5, "domain": "urban_governance", "element": "facility",
     "area": "西陵-夷陵桥", "address_hint": "西陵区夷陵长江大桥"},
    {"name": "宜昌长江大桥", "level1": "交通设施", "level2": "桥",
     "lng": 111.3780, "lat": 30.7280, "weight": 0.5, "domain": "urban_governance", "element": "facility",
     "area": "伍家-宜昌桥", "address_hint": "伍家岗区宜昌长江大桥"},
    {"name": "伍家岗长江大桥", "level1": "交通设施", "level2": "桥",
     "lng": 111.4010, "lat": 30.7360, "weight": 0.5, "domain": "urban_planning", "element": "facility",
     "area": "伍家-伍家桥", "address_hint": "伍家岗区伍家岗长江大桥"},
    {"name": "至喜长江大桥", "level1": "交通设施", "level2": "桥",
     "lng": 111.2450, "lat": 30.6900, "weight": 0.5, "domain": "urban_planning", "element": "facility",
     "area": "西陵-至喜桥", "address_hint": "西陵区至喜长江大桥"},
    {"name": "东山大道 BRT 站", "level1": "交通设施", "level2": "公交车站",
     "lng": 111.3040, "lat": 30.7000, "weight": 0.6, "domain": "urban_governance", "element": "facility",
     "area": "西陵-BRT", "address_hint": "西陵区东山大道 BRT 站"},
    {"name": "沿江大道 BRT 站", "level1": "交通设施", "level2": "公交车站",
     "lng": 111.3060, "lat": 30.7000, "weight": 0.6, "domain": "urban_governance", "element": "facility",
     "area": "西陵-BRT", "address_hint": "西陵区沿江大道 BRT 站"},
    {"name": "夷陵大道 BRT 站", "level1": "交通设施", "level2": "公交车站",
     "lng": 111.3080, "lat": 30.6980, "weight": 0.5, "domain": "urban_governance", "element": "facility",
     "area": "西陵-BRT", "address_hint": "西陵区夷陵大道 BRT 站"},
    {"name": "发展大道 BRT 站", "level1": "交通设施", "level2": "公交车站",
     "lng": 111.3320, "lat": 30.7130, "weight": 0.5, "domain": "urban_governance", "element": "facility",
     "area": "伍家-BRT", "address_hint": "伍家岗区发展大道 BRT 站"},
    {"name": "城东大道 BRT 站", "level1": "交通设施", "level2": "公交车站",
     "lng": 111.3540, "lat": 30.7200, "weight": 0.5, "domain": "urban_governance", "element": "facility",
     "area": "伍家-BRT", "address_hint": "伍家岗区城东大道 BRT 站"},
    {"name": "中建·宜昌之星 BRT 站", "level1": "交通设施", "level2": "公交车站",
     "lng": 111.3690, "lat": 30.7300, "weight": 0.4, "domain": "urban_governance", "element": "facility",
     "area": "伍家-BRT", "address_hint": "伍家岗区中建宜昌之星 BRT 站"},
    {"name": "宜昌公交集团", "level1": "交通设施", "level2": "公交车站",
     "lng": 111.3060, "lat": 30.6990, "weight": 0.4, "domain": "urban_governance", "element": "facility",
     "area": "西陵-公交", "address_hint": "西陵区公交集团"},
    {"name": "中石化加油站（CBD）", "level1": "交通设施", "level2": "加油加气站",
     "lng": 111.3140, "lat": 30.7030, "weight": 0.3, "domain": "urban_operation", "element": "facility",
     "area": "西陵-加油站", "address_hint": "西陵区中石化加油站"},
    {"name": "中石油加油站（伍家）", "level1": "交通设施", "level2": "加油加气站",
     "lng": 111.3650, "lat": 30.7320, "weight": 0.3, "domain": "urban_operation", "element": "facility",
     "area": "伍家-加油站", "address_hint": "伍家岗区中石油加油站"},
    {"name": "特来电充电站（CBD）", "level1": "交通设施", "level2": "充电站",
     "lng": 111.3120, "lat": 30.7030, "weight": 0.3, "domain": "urban_planning", "element": "facility",
     "area": "西陵-充电站", "address_hint": "西陵区特来电充电站"},
    {"name": "伍家岗公共停车场", "level1": "交通设施", "level2": "停车场",
     "lng": 111.3650, "lat": 30.7290, "weight": 0.4, "domain": "urban_governance", "element": "facility",
     "area": "伍家-停车场", "address_hint": "伍家岗区公共停车场"},

    # ============= 公园与文旅 =============
    {"name": "滨江公园", "level1": "旅游景点", "level2": "公园",
     "lng": 111.2880, "lat": 30.6930, "weight": 1.5, "domain": "urban_operation", "element": "environment",
     "area": "西陵-滨江", "address_hint": "西陵区滨江公园", "radius_m": 500},
    {"name": "滨江公园（双亭广场）", "level1": "旅游景点", "level2": "公园",
     "lng": 111.2920, "lat": 30.6940, "weight": 1.0, "domain": "urban_operation", "element": "environment",
     "area": "西陵-滨江", "address_hint": "西陵区滨江公园双亭广场"},
    {"name": "滨江公园（镇江阁）", "level1": "旅游景点", "level2": "景点",
     "lng": 111.2850, "lat": 30.6920, "weight": 1.0, "domain": "urban_operation", "element": "environment",
     "area": "西陵-滨江", "address_hint": "西陵区镇江阁"},
    {"name": "东山公园", "level1": "旅游景点", "level2": "公园",
     "lng": 111.3270, "lat": 30.7180, "weight": 1.3, "domain": "urban_operation", "element": "environment",
     "area": "伍家-东山", "address_hint": "伍家岗区东山公园", "radius_m": 700},
    {"name": "磨基山森林公园", "level1": "旅游景点", "level2": "风景区",
     "lng": 111.3250, "lat": 30.7090, "weight": 1.0, "domain": "urban_operation", "element": "environment",
     "area": "西陵-磨基山", "address_hint": "西陵区磨基山森林公园", "radius_m": 600},
    {"name": "儿童公园", "level1": "旅游景点", "level2": "公园",
     "lng": 111.2880, "lat": 30.6930, "weight": 0.8, "domain": "urban_operation", "element": "environment",
     "area": "西陵-儿童公园", "address_hint": "西陵区儿童公园"},
    {"name": "城东公园", "level1": "旅游景点", "level2": "公园",
     "lng": 111.3460, "lat": 30.7220, "weight": 0.7, "domain": "urban_operation", "element": "environment",
     "area": "伍家-城东", "address_hint": "伍家岗区城东公园"},
    {"name": "求索公园", "level1": "旅游景点", "level2": "公园",
     "lng": 111.3500, "lat": 30.7270, "weight": 0.6, "domain": "urban_operation", "element": "environment",
     "area": "伍家-求索", "address_hint": "伍家岗区求索公园"},
    {"name": "和平公园", "level1": "旅游景点", "level2": "公园",
     "lng": 111.3130, "lat": 30.7020, "weight": 0.6, "domain": "urban_operation", "element": "environment",
     "area": "西陵-和平", "address_hint": "西陵区和平公园"},
    {"name": "三峡博物馆", "level1": "文化传媒", "level2": "博物馆",
     "lng": 111.2850, "lat": 30.6940, "weight": 1.0, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-博物馆", "address_hint": "西陵区三峡博物馆"},
    {"name": "宜昌市规划展览馆", "level1": "文化传媒", "level2": "展览馆",
     "lng": 111.2900, "lat": 30.6950, "weight": 0.7, "domain": "urban_planning", "element": "culture",
     "area": "西陵-规划馆", "address_hint": "西陵区规划展览馆"},
    {"name": "宜昌市美术馆", "level1": "文化传媒", "level2": "美术馆",
     "lng": 111.2870, "lat": 30.6930, "weight": 0.5, "domain": "urban_operation", "element": "culture",
     "area": "西陵-美术馆", "address_hint": "西陵区美术馆"},
    {"name": "宜昌市图书馆", "level1": "教育培训", "level2": "图书馆",
     "lng": 111.2890, "lat": 30.6950, "weight": 0.6, "domain": "urban_operation", "element": "service",
     "area": "西陵-图书馆", "address_hint": "西陵区图书馆"},
    {"name": "宜昌科技馆", "level1": "教育培训", "level2": "科技馆",
     "lng": 111.2850, "lat": 30.6930, "weight": 0.5, "domain": "urban_operation", "element": "service",
     "area": "西陵-科技馆", "address_hint": "西陵区科技馆"},
    {"name": "西陵区文化馆", "level1": "文化传媒", "level2": "文化宫",
     "lng": 111.2750, "lat": 30.6900, "weight": 0.6, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-二马路", "address_hint": "西陵区二马路西陵区文化馆"},
    {"name": "屈原文化园", "level1": "文化传媒", "level2": "展览馆",
     "lng": 111.2910, "lat": 30.6920, "weight": 0.5, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-屈原园", "address_hint": "西陵区屈原文化园"},

    # ============= 美食与娱乐 =============
    {"name": "中影国际影城（CBD）", "level1": "休闲娱乐", "level2": "电影院",
     "lng": 111.3140, "lat": 30.7030, "weight": 0.7, "domain": "urban_operation", "element": "event",
     "area": "西陵-影院", "address_hint": "西陵区中影国际影城"},
    {"name": "万达影城（CBD）", "level1": "休闲娱乐", "level2": "电影院",
     "lng": 111.3120, "lat": 30.7020, "weight": 0.7, "domain": "urban_operation", "element": "event",
     "area": "西陵-万达影城", "address_hint": "西陵区万达影城"},
    {"name": "横店影视（伍家）", "level1": "休闲娱乐", "level2": "电影院",
     "lng": 111.3680, "lat": 30.7280, "weight": 0.5, "domain": "urban_operation", "element": "event",
     "area": "伍家-影院", "address_hint": "伍家岗区横店影视"},
    {"name": "麦颂 KTV", "level1": "休闲娱乐", "level2": "ktv",
     "lng": 111.3100, "lat": 30.7000, "weight": 0.4, "domain": "urban_operation", "element": "event",
     "area": "西陵-KTV", "address_hint": "西陵区麦颂 KTV"},
    {"name": "米乐星 KTV（伍家）", "level1": "休闲娱乐", "level2": "ktv",
     "lng": 111.3660, "lat": 30.7270, "weight": 0.4, "domain": "urban_operation", "element": "event",
     "area": "伍家-KTV", "address_hint": "伍家岗区米乐星 KTV"},
    {"name": "星动健身（CBD）", "level1": "运动健身", "level2": "健身中心",
     "lng": 111.3110, "lat": 30.7020, "weight": 0.5, "domain": "urban_operation", "element": "service",
     "area": "西陵-健身", "address_hint": "西陵区星动健身"},
    {"name": "奥体中心", "level1": "运动健身", "level2": "体育场馆",
     "lng": 111.3410, "lat": 30.7330, "weight": 0.6, "domain": "urban_operation", "element": "event",
     "area": "伍家-奥体", "address_hint": "伍家岗区奥体中心"},
    {"name": "屈原国际大酒店", "level1": "酒店", "level2": "星级酒店",
     "lng": 111.2860, "lat": 30.6940, "weight": 0.6, "domain": "urban_operation", "element": "service",
     "area": "西陵-酒店", "address_hint": "西陵区屈原国际大酒店"},
    {"name": "宜昌万达瑞华酒店", "level1": "酒店", "level2": "星级酒店",
     "lng": 111.3130, "lat": 30.7030, "weight": 0.5, "domain": "urban_operation", "element": "service",
     "area": "西陵-瑞华", "address_hint": "西陵区万达瑞华酒店"},
    {"name": "宜昌均瑶禧玥酒店", "level1": "酒店", "level2": "星级酒店",
     "lng": 111.3030, "lat": 30.7000, "weight": 0.5, "domain": "urban_operation", "element": "service",
     "area": "西陵-禧玥", "address_hint": "西陵区均瑶禧玥酒店"},
    {"name": "锦江都城（西陵）", "level1": "酒店", "level2": "快捷酒店",
     "lng": 111.2920, "lat": 30.6950, "weight": 0.4, "domain": "urban_operation", "element": "service",
     "area": "西陵-锦江", "address_hint": "西陵区锦江都城"},
    {"name": "汉庭酒店（伍家）", "level1": "酒店", "level2": "快捷酒店",
     "lng": 111.3630, "lat": 30.7300, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "伍家-汉庭", "address_hint": "伍家岗区汉庭酒店"},
    {"name": "桔子水晶（CBD）", "level1": "酒店", "level2": "快捷酒店",
     "lng": 111.3100, "lat": 30.7000, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "西陵-桔子", "address_hint": "西陵区桔子水晶酒店"},

    # ============= 金融 =============
    {"name": "工商银行（西陵支行）", "level1": "金融", "level2": "银行",
     "lng": 111.2980, "lat": 30.7000, "weight": 0.4, "domain": "urban_operation", "element": "service",
     "area": "西陵-工行", "address_hint": "西陵区工商银行支行"},
    {"name": "建设银行（CBD 支行）", "level1": "金融", "level2": "银行",
     "lng": 111.3110, "lat": 30.7020, "weight": 0.4, "domain": "urban_operation", "element": "service",
     "area": "西陵-建行", "address_hint": "西陵区建设银行 CBD 支行"},
    {"name": "农业银行（伍家支行）", "level1": "金融", "level2": "银行",
     "lng": 111.3640, "lat": 30.7280, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "伍家-农行", "address_hint": "伍家岗区农业银行"},
    {"name": "中国银行（CBD）", "level1": "金融", "level2": "银行",
     "lng": 111.3120, "lat": 30.7010, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "西陵-中行", "address_hint": "西陵区中国银行"},
    {"name": "招商银行（CBD）", "level1": "金融", "level2": "银行",
     "lng": 111.3130, "lat": 30.7030, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "西陵-招行", "address_hint": "西陵区招商银行"},
    {"name": "湖北银行（伍家）", "level1": "金融", "level2": "银行",
     "lng": 111.3620, "lat": 30.7290, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "伍家-湖北行", "address_hint": "伍家岗区湖北银行"},
    {"name": "邮储银行（西陵）", "level1": "金融", "level2": "银行",
     "lng": 111.2900, "lat": 30.6930, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "西陵-邮储", "address_hint": "西陵区邮储银行"},

    # ============= 居住社区 =============
    {"name": "东山花园", "level1": "房地产", "level2": "住宅区",
     "lng": 111.3320, "lat": 30.7180, "weight": 0.9, "domain": "urban_renewal", "element": "service",
     "area": "伍家-东山花园", "address_hint": "伍家岗区东山花园", "radius_m": 600},
    {"name": "伍家岗住宅区", "level1": "房地产", "level2": "住宅区",
     "lng": 111.3650, "lat": 30.7330, "weight": 0.8, "domain": "urban_renewal", "element": "service",
     "area": "伍家-住宅", "address_hint": "伍家岗区住宅片区", "radius_m": 700},
    {"name": "伍家北住宅区", "level1": "房地产", "level2": "住宅区",
     "lng": 111.3800, "lat": 30.7480, "weight": 0.6, "domain": "urban_renewal", "element": "service",
     "area": "伍家-北住宅", "address_hint": "伍家岗区北住宅片区", "radius_m": 800},
    {"name": "西陵老居住区", "level1": "房地产", "level2": "住宅区",
     "lng": 111.2790, "lat": 30.6900, "weight": 0.9, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-老居住", "address_hint": "西陵区老居住片区", "radius_m": 600},
    {"name": "CBD 高层住宅区", "level1": "房地产", "level2": "住宅区",
     "lng": 111.3140, "lat": 30.7030, "weight": 0.7, "domain": "urban_planning", "element": "service",
     "area": "西陵-CBD住宅", "address_hint": "西陵区 CBD 高层住宅", "radius_m": 400},
    {"name": "上上城", "level1": "房地产", "level2": "住宅区",
     "lng": 111.2880, "lat": 30.6910, "weight": 0.6, "domain": "urban_renewal", "element": "service",
     "area": "西陵-上上城", "address_hint": "西陵区上上城"},
    {"name": "香格里拉花园", "level1": "房地产", "level2": "住宅区",
     "lng": 111.3500, "lat": 30.7270, "weight": 0.6, "domain": "urban_operation", "element": "service",
     "area": "伍家-香格里拉", "address_hint": "伍家岗区香格里拉花园"},
    {"name": "中建宜昌之星", "level1": "房地产", "level2": "住宅区",
     "lng": 111.3690, "lat": 30.7300, "weight": 0.7, "domain": "urban_planning", "element": "service",
     "area": "伍家-中建星", "address_hint": "伍家岗区中建宜昌之星"},
    {"name": "二马路老社区（西陵）", "level1": "房地产", "level2": "住宅区",
     "lng": 111.2750, "lat": 30.6890, "weight": 1.4, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-二马路社区", "address_hint": "西陵区二马路老社区", "radius_m": 300},

    # ============= 二马路内部细致分布 =============
    {"name": "二马路 1 号院落（拟改造）", "level1": "房地产", "level2": "住宅区",
     "lng": 111.2755, "lat": 30.6885, "weight": 0.8, "domain": "urban_renewal", "element": "facility",
     "area": "西陵-二马路", "address_hint": "西陵区二马路 1 号院"},
    {"name": "二马路 8 号老茶馆", "level1": "美食", "level2": "茶座",
     "lng": 111.2760, "lat": 30.6880, "weight": 0.8, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-二马路", "address_hint": "西陵区二马路 8 号"},
    {"name": "二马路非遗工坊", "level1": "文化传媒", "level2": "艺术团体",
     "lng": 111.2745, "lat": 30.6875, "weight": 0.9, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-二马路", "address_hint": "西陵区二马路非遗工坊"},
    {"name": "二马路 18 号文创店", "level1": "购物", "level2": "商铺",
     "lng": 111.2770, "lat": 30.6880, "weight": 0.7, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-二马路", "address_hint": "西陵区二马路 18 号文创"},
    {"name": "二马路改造指挥部", "level1": "政府机构", "level2": "行政单位",
     "lng": 111.2755, "lat": 30.6887, "weight": 0.6, "domain": "urban_renewal", "element": "facility",
     "area": "西陵-二马路", "address_hint": "西陵区二马路改造指挥部"},
    {"name": "红星路 12 号民居", "level1": "房地产", "level2": "住宅区",
     "lng": 111.2800, "lat": 30.6900, "weight": 0.7, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-红星路", "address_hint": "西陵区红星路 12 号"},
    {"name": "献福路社区中心", "level1": "生活服务", "level2": "家政服务",
     "lng": 111.2740, "lat": 30.6890, "weight": 0.6, "domain": "urban_renewal", "element": "service",
     "area": "西陵-献福路", "address_hint": "西陵区献福路社区"},
    {"name": "大南门老茶馆（网红）", "level1": "美食", "level2": "茶座",
     "lng": 111.2725, "lat": 30.6855, "weight": 1.2, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-大南门", "address_hint": "西陵区大南门老茶馆"},
    {"name": "大南门 5 号历史建筑", "level1": "旅游景点", "level2": "文物古迹",
     "lng": 111.2720, "lat": 30.6850, "weight": 1.0, "domain": "urban_renewal", "element": "culture",
     "area": "西陵-大南门", "address_hint": "西陵区大南门 5 号历史建筑"},

    # ============= 滨江带细致分布 =============
    {"name": "滨江步道（西陵段）", "level1": "旅游景点", "level2": "景点",
     "lng": 111.2960, "lat": 30.6960, "weight": 1.0, "domain": "urban_operation", "element": "environment",
     "area": "西陵-滨江步道", "address_hint": "西陵区滨江步道"},
    {"name": "滨江夜市（西陵段）", "level1": "美食", "level2": "小吃快餐店",
     "lng": 111.2900, "lat": 30.6940, "weight": 1.3, "domain": "urban_operation", "element": "event",
     "area": "西陵-滨江夜市", "address_hint": "西陵区滨江夜市"},
    {"name": "长江沿线（伍家段）", "level1": "交通设施", "level2": "港口",
     "lng": 111.3360, "lat": 30.7220, "weight": 0.5, "domain": "urban_operation", "element": "environment",
     "area": "伍家-长江沿线", "address_hint": "伍家岗区长江沿线"},
    {"name": "至喜长江大桥北", "level1": "交通设施", "level2": "桥",
     "lng": 111.2450, "lat": 30.6905, "weight": 0.4, "domain": "urban_governance", "element": "facility",
     "area": "西陵-至喜桥北", "address_hint": "西陵区至喜长江大桥北"},
    {"name": "沿江大道（西陵段）", "level1": "道路", "level2": "城市主干道",
     "lng": 111.3000, "lat": 30.6980, "weight": 0.6, "domain": "urban_governance", "element": "facility",
     "area": "西陵-沿江大道", "address_hint": "西陵区沿江大道"},
    {"name": "东山大道（西陵段）", "level1": "道路", "level2": "城市主干道",
     "lng": 111.3040, "lat": 30.7000, "weight": 0.5, "domain": "urban_governance", "element": "facility",
     "area": "西陵-东山大道", "address_hint": "西陵区东山大道"},
    {"name": "夷陵大道（伍家段）", "level1": "道路", "level2": "城市主干道",
     "lng": 111.3320, "lat": 30.7130, "weight": 0.5, "domain": "urban_governance", "element": "facility",
     "area": "伍家-夷陵大道", "address_hint": "伍家岗区夷陵大道"},

    # ============= 政务/治理/应急 =============
    {"name": "宜昌市消防支队", "level1": "政府机构", "level2": "公检法机构",
     "lng": 111.3060, "lat": 30.7000, "weight": 0.3, "domain": "urban_governance", "element": "facility",
     "area": "西陵-消防", "address_hint": "西陵区消防支队"},
    {"name": "西陵区消防大队", "level1": "政府机构", "level2": "公检法机构",
     "lng": 111.2850, "lat": 30.6920, "weight": 0.3, "domain": "urban_governance", "element": "facility",
     "area": "西陵-消防大队", "address_hint": "西陵区消防大队"},
    {"name": "伍家岗消防大队", "level1": "政府机构", "level2": "公检法机构",
     "lng": 111.3680, "lat": 30.7320, "weight": 0.3, "domain": "urban_governance", "element": "facility",
     "area": "伍家-消防", "address_hint": "伍家岗区消防大队"},
    {"name": "西陵区城管执法大队", "level1": "政府机构", "level2": "公检法机构",
     "lng": 111.2940, "lat": 30.6940, "weight": 0.3, "domain": "urban_governance", "element": "facility",
     "area": "西陵-城管执法", "address_hint": "西陵区城管执法大队"},
    {"name": "伍家岗区城管执法大队", "level1": "政府机构", "level2": "公检法机构",
     "lng": 111.3650, "lat": 30.7340, "weight": 0.3, "domain": "urban_governance", "element": "facility",
     "area": "伍家-城管执法", "address_hint": "伍家岗区城管执法大队"},
    {"name": "环卫中心（西陵）", "level1": "政府机构", "level2": "行政单位",
     "lng": 111.2840, "lat": 30.6910, "weight": 0.3, "domain": "urban_governance", "element": "facility",
     "area": "西陵-环卫", "address_hint": "西陵区环卫中心"},
    {"name": "市政设施维护中心", "level1": "政府机构", "level2": "行政单位",
     "lng": 111.2920, "lat": 30.6930, "weight": 0.3, "domain": "urban_governance", "element": "facility",
     "area": "西陵-市政", "address_hint": "西陵区市政设施维护中心"},
    {"name": "防汛抗旱指挥部（西陵）", "level1": "政府机构", "level2": "行政单位",
     "lng": 111.2910, "lat": 30.6910, "weight": 0.3, "domain": "urban_governance", "element": "facility",
     "area": "西陵-防汛", "address_hint": "西陵区防汛抗旱指挥部"},
    {"name": "应急避难场所（滨江公园）", "level1": "政府机构", "level2": "福利机构",
     "lng": 111.2880, "lat": 30.6930, "weight": 0.3, "domain": "urban_governance", "element": "facility",
     "area": "西陵-应急", "address_hint": "西陵区应急避难场所"},
    {"name": "应急避难场所（东山公园）", "level1": "政府机构", "level2": "福利机构",
     "lng": 111.3270, "lat": 30.7180, "weight": 0.3, "domain": "urban_governance", "element": "facility",
     "area": "伍家-应急", "address_hint": "伍家岗区应急避难场所"},

    # ============= 公司/产业园区 =============
    {"name": "宜昌高新区产业园", "level1": "公司企业", "level2": "园区",
     "lng": 111.4120, "lat": 30.7480, "weight": 0.6, "domain": "urban_planning", "element": "service",
     "area": "伍家-高新区", "address_hint": "伍家岗区高新区产业园", "radius_m": 800},
    {"name": "西陵工业园", "level1": "公司企业", "level2": "园区",
     "lng": 111.2800, "lat": 30.6970, "weight": 0.4, "domain": "urban_planning", "element": "service",
     "area": "西陵-工业园", "address_hint": "西陵区工业园"},
    {"name": "兴发集团总部", "level1": "公司企业", "level2": "公司",
     "lng": 111.2950, "lat": 30.6990, "weight": 0.4, "domain": "urban_planning", "element": "service",
     "area": "西陵-兴发", "address_hint": "西陵区兴发集团"},
    {"name": "安琪酵母总部", "level1": "公司企业", "level2": "公司",
     "lng": 111.2930, "lat": 30.7000, "weight": 0.3, "domain": "urban_planning", "element": "service",
     "area": "西陵-安琪", "address_hint": "西陵区安琪酵母"},
    {"name": "宜昌传媒中心", "level1": "文化传媒", "level2": "新闻出版",
     "lng": 111.2870, "lat": 30.6950, "weight": 0.4, "domain": "urban_operation", "element": "service",
     "area": "西陵-传媒", "address_hint": "西陵区宜昌传媒中心"},
    {"name": "三峡广电中心", "level1": "文化传媒", "level2": "广播电视",
     "lng": 111.2900, "lat": 30.6980, "weight": 0.4, "domain": "urban_operation", "element": "service",
     "area": "西陵-广电", "address_hint": "西陵区三峡广电中心"},

    # ============= 补充生活服务 =============
    {"name": "中国移动（西陵营业厅）", "level1": "生活服务", "level2": "通讯营业厅",
     "lng": 111.2980, "lat": 30.6980, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "西陵-移动", "address_hint": "西陵区中国移动"},
    {"name": "中国联通（CBD）", "level1": "生活服务", "level2": "通讯营业厅",
     "lng": 111.3110, "lat": 30.7020, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "西陵-联通", "address_hint": "西陵区中国联通"},
    {"name": "中国电信（伍家）", "level1": "生活服务", "level2": "通讯营业厅",
     "lng": 111.3640, "lat": 30.7280, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "伍家-电信", "address_hint": "伍家岗区中国电信"},
    {"name": "西陵区邮政支局", "level1": "生活服务", "level2": "邮局",
     "lng": 111.2900, "lat": 30.6920, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "西陵-邮政", "address_hint": "西陵区邮政支局"},
    {"name": "顺丰快递（CBD）", "level1": "生活服务", "level2": "物流公司",
     "lng": 111.3120, "lat": 30.7020, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "西陵-顺丰", "address_hint": "西陵区顺丰快递"},
    {"name": "京东物流（伍家）", "level1": "生活服务", "level2": "物流公司",
     "lng": 111.3740, "lat": 30.7330, "weight": 0.3, "domain": "urban_operation", "element": "service",
     "area": "伍家-京东", "address_hint": "伍家岗区京东物流"},
    {"name": "美团外卖站（西陵）", "level1": "生活服务", "level2": "其他",
     "lng": 111.3000, "lat": 30.6980, "weight": 0.4, "domain": "urban_operation", "element": "service",
     "area": "西陵-美团", "address_hint": "西陵区美团外卖站"},
    {"name": "饿了么外卖站（伍家）", "level1": "生活服务", "level2": "其他",
     "lng": 111.3700, "lat": 30.7280, "weight": 0.4, "domain": "urban_operation", "element": "service",
     "area": "伍家-饿了么", "address_hint": "伍家岗区饿了么外卖站"},
]
